export type Type = {
	'body-xs-regular': string;
	'body-xs-medium': string;
	'body-xs-bold': string;
	'body-s-regular': string;
	'body-s-medium': string;
	'body-s-bold': string;
	'body-m-regular': string;
	'body-m-medium': string;
	'body-m-bold': string;
	'body-l-regular': string;
	'body-l-medium': string;
	'body-l-bold': string;
	'body-xl-regular': string;
	'body-xl-medium': string;
	'body-xl-bold': string;
	h1: string;
	h2: string;
	h3: string;
	h4: string;
	h5: string;
	h6: string;
};
